### ISSUE TITLE
Error initializing Wakatime: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by alexvremja** [gandarez/ssms-wakatime#13]
Hi!
I'm sure I've done the installing procedure in the correct way but in logs I have this:

`2018-09-14 19:35:52.3064|INFO|WakaTime.Logger|Initializing WakaTime v1.0.3
2018-09-14 19:35:53.0935|ERROR|WakaTime.Logger|Error initializing Wakatime: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at WakaTime.Downloader.DownloadCli(String url, String dir)
   at WakaTime.WakaTime.OnConnection(Object application, ext_ConnectMode connectMode, Object addInInst, Array& custom)`

using ssms 2014

can suggest the reason

**Comment by jnickle** [comment]
I've installed python 3.7 (64bit) on Windows 10.  Restarted SQL Server and still get the same "Let's download and install python now?" pop up ....

**Comment by jnickle** [comment]
Anyone ? Do I need a different version of Python installed?

**Comment by joseetmanuel** [comment]
It seems that it is in windows 10 the error to enable the ssl 2.0, has anyone tried to install it in w7?

**Comment by alexvremja** [comment]
I'm Using Windows Server 2012 R2, therefore probably problem is with whole Windows OSs

**Comment by gandarez** [comment]
Just released a new version to support v2012+

Download and follow the instructions
https://github.com/gandarez/ssms-wakatime/releases/tag/v2.0.0
